[package]
name = "deepmesa-examples"
version = "0.1.0"
authors = ["Rahul Singh <rsingh@arrsingh.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deepmesa = "^0.4.0"